version: '3.8'

services:
  vpm1:
    build:
      context: .
      dockerfile: VPM/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - INSTANCE_NAME=vpm1

  vpm2:
    build:
      context: .
      dockerfile: VPM/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - INSTANCE_NAME=vpm2

  vpm3:
    build:
      context: .
      dockerfile: VPM/Dockerfile
    ports:
      - "8083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - INSTANCE_NAME=vpm3 